sonar.projectKey=MariyappanSubramaniyan_Mariyappan---Sonar--Cloud
sonar.organization=mariyappansubramaniyan-1

sonar.host.url = https://sonarcloud.io
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=./src
sonar.exclusions=**/*
sonar.language=ts
